### ISSUE TITLE
proves_and_proved_by might be wrong?

### ISSUE THREAD

**Issue by Charlier-pi** [evhub/pyprover#3]
Thanks for this awesome library. But I think maybe the following results are wrong?

```python
In [4]: from pyprover import *

In [5]: f1 = '∃y,∃z,∀x, (Q(x,z)->Q(y,x))'
   ...: f2 = '∀y,∃x, ((R(x,z)∧R(x))->R(y))'
   ...: print(proves_and_proved_by(expr(f1),expr(f2)))
True

```
these two are not equal, right?

```python
In [2]: from pyprover import *
   ...: f1 = '∀z,∃x, ¬((Q(z)∧Q(x)))'
   ...: f2 = '∃z,∀x, ¬((Q(x)∧Q(z)))'
   ...: print(proves_and_proved_by(expr(f1),expr(f2)))
True

```
these two are also not equal, right?

**Comment by evhub** [comment]
@qzhongmun Try upgrading with `pip install -U pyprover>=0.6.0` and using `strict_proves_and_proved_by` instead—that should give you what you want.

**Comment by Eva-Zi** [comment]
@evhub Thanks so much for your response. It works!

**Comment by evhub** [comment]
For future record, the difference between strict and non-strict versions is that the non-strict versions assume `EX x, top`, which, if that's not an assumption you want to make, can be confusing. The reason for that is that resolution is only guaranteed to work in the case where you are willing to make that assumption, so `pyprover` makes it for you by default.
