### ISSUE TITLE
bugs in find_unification?

### ISSUE THREAD

**Issue by rudaoshi** [evhub/pyprover#4]
```python
>> x = Var('x')
>> y = Var('y')  

>> (Q(x)).find_unification(Q(a))
>> {Var("x"): Const("a")}

>> (Q(x) & P(y)).find_unification((Q(a) & P(b)))
>> 

```

That is, ` (Q(x) & P(y)).find_unification((Q(a) & P(b)))` output None.

I think there is something wrong with the find_unification.

**Comment by evhub** [comment]
`find_unification` isn't meant to work on Boolean operators since it's not necessary when doing resolution in conjunctive normal form, but it's easy enough to add, so I'm labeling this as an enhancement rather than a bug.

**Comment by evhub** [comment]
This works now in `pyprover>=0.6.1`.

**Comment by rudaoshi** [comment]
Thank you for the quick response and update.
